#ifndef NANOARROW_CONFIG_H_INCLUDED
#define NANOARROW_CONFIG_H_INCLUDED
#define NANOARROW_VERSION_MAJOR 0
#define NANOARROW_VERSION_MINOR 8
#define NANOARROW_VERSION_PATCH 0
#define NANOARROW_VERSION "0.8.0"
#define NANOARROW_VERSION_INT \
  (NANOARROW_VERSION_MAJOR * 10000 + NANOARROW_VERSION_MINOR * 100 + NANOARROW_VERSION_PATCH)
#endif
